---
- hosts: kubernetes
  user: ansadmin
  tasks:
    - name: create docker image
      command: sudo kubectl apply -f mongo-config.yaml

    - name: create docker image
      command: sudo kubectl apply -f mongo-secret.yaml

    - name: create docker image
      command: sudo kubectl apply -f api-deployment.yaml

    - name: create docker image
      command: sudo kubectl apply -f mongo-deployment.yaml